### ISSUE TITLE
Checklist of Things to Complete and Expected Finish

### ISSUE THREAD

**Issue by kdgbsn** [brianquimio/cs373-idb#47]
General _[2 Mon]_
- [x] .gitignore
- [x] .travis.yml _[1 Thurs]_
- [x] makefile
- [x] apiary.apib (from Apiary) _[1 Tues]_
- [x] IDB3.log (output of git log with at least 15 commits)
- [x] models.html (output of pydoc3)
- [x] UML.pdf (UML diagram)
- [x] technical report _[2 Mon]_
- [x] search functionality _[1 Sat]_
- [ ] presentation (on SpeakerDeck) _[2 Mon]_
- [ ] self-critique _[2 Mon]_
- [ ] exercise of Stealth Mode's API (http://series-z.org/) _[2 Sun]_
- [ ] critique of Stealth Mode's website _[2 Mon]_

Back End _[1 Fri]_
- [x] app.py (routing) _[1 Wed]_
- [x] models.py (ORM || MySQL) _[1 Tues]_
- [x] JSONs returning from DB _[1 Fri]_
- [x] app/tests.py (average of 3 unit tests per function/method, run coverage3) _[1 Fri]_
- [x] Deployment documentation _[1 Wed]_

Front End _[1 Thurs]_
- [x] index.html (with nav, foot, and ng-view) _[1 Wed]_
- [x] states.html (with table and ng-bind) _[1 Wed]_
- [x] cities.html (with table and ng-bind) _[1 Wed]_
- [x] neighborhoods.html (with table and ng-bind) _[1 Wed]_
- [x] single_model.html (with 2 tables, map, and ng-bind) _[1 Wed]_
- [x] about.html (with people, stats, data, tools, and unit test button) _[1 Wed]_
- [ ] table.html ? could be good for a directive _[1 Wed]_
- [ ] map.html ? could be good for a directive _[1 Wed]_
- [x] app.js (routing) _[1 Thurs]_
- [ ] controllers.js (one per page type) _[1 Thurs]_
- [ ] services.js (table, map, stats) _[1 Wed]_
- [ ] directives.js (if needed) _[1 Thurs]_

**Comment by shperl** [comment]
JSONs are returning.

2 caveats to resolve for completion: 
- currently on non-incognito browsers there is an issue with the DNS or front end routing causing HTML templates to be surved on API pages.
- the neighborhood_stats.json file needs to be resolved
